# Generated by Django 5.2.7 on 2025-10-30 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('father_mobile', models.CharField(max_length=15)),
                ('father_email', models.EmailField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('mother_mobile', models.CharField(max_length=15)),
                ('mother_email', models.EmailField(max_length=100)),
                ('present_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('student_class', models.CharField(max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('admission_number', models.CharField(blank=True, max_length=15)),
                ('section', models.CharField(blank=True, max_length=15)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student/')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student.parent')),
            ],
        ),
    ]
