# Generated by Django 5.2.7 on 2025-11-03 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('exam_name', models.CharField(max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='student.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student', 'subject', 'exam_name'],
                'unique_together': {('student', 'subject', 'exam_name')},
            },
        ),
    ]
