# Generated by Django 5.2.7 on 2025-11-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_assignment_options_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
