# Generated by Django 5.2.7 on 2025-11-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Q6svjW5ed3I1skb5PqXSMsxLkRBvHbSy', editable=False, max_length=32, unique=True),
        ),
    ]
