# Generated by Django 5.2.7 on 2025-11-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='NjRMf428M6Y5tj0sgg1qB9UNHafs6CtY', editable=False, max_length=32, unique=True),
        ),
    ]
