# Generated by Django 5.2.7 on 2025-11-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0007_customuser_avatar_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='sGTaYNUiTRApAZW1kJgSTqXmbY9VjJDM', editable=False, max_length=32, unique=True),
        ),
    ]
